apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filament-inventory-tracker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
